### ISSUE TITLE
error processing bioconcepts2pubtator_offsets.gz

### ISSUE THREAD

**Issue by kengcher** [greenelab/pubtator#18]
Hi

I would like to try out pubtator and was running execute.sh and it gave an error:

~/pubtator$ python scripts/pubtator_to_xml.py --documents download/bioconcepts2pubtator_offsets.gz --output data/pubtator-docs.xml.xz
5079543it [2:57:28, 370.11it/s]Traceback (most recent call last):
  File "scripts/pubtator_to_xml.py", line 205, in <module>
    convert_pubtator(args.documents, args.output)
  File "scripts/pubtator_to_xml.py", line 164, in convert_pubtator
    for article in tqdm.tqdm(article_generator):
  File "/home/ksoh/anaconda3/envs/pubtator/lib/python3.8/site-packages/tqdm/std.py", line 1093, in __iter__
    for obj in iterable:
  File "scripts/pubtator_to_xml.py", line 131, in read_bioconcepts2pubtator_offsets
    yield pubtator_stanza_to_article(g)
  File "scripts/pubtator_to_xml.py", line 101, in pubtator_stanza_to_article
    annts = list(annts)
  File "/home/ksoh/anaconda3/envs/pubtator/lib/python3.8/csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: line contains NUL
5079543it [2:57:28, 477.03it/s]

pls advise. Thank you.

**Comment by danich1** [comment]
Greetings,

Looks like there is a floating NULL character(s) within the `bioconcepts2pubtator_offsets.gz` file. This is causing the csv module to throw an error. Not sure if this is a version issue or a file reader issue, but a quick fix is to replace the following line of code in pubtator_to_xml.py script:

``` python 
annts = csv.DictReader(lines[2:], fieldnames=['pubmed_id', 'start', 'end', 'term', 'type', 'tag_id'], delimiter="\t", quoting=csv.QUOTE_NONE)
```
with 
```python
fixed_lines = [str_with_null.replace('\x00', '') for str_with_null in lines[2:]]
annts = csv.DictReader(fixed_lines, fieldnames=['pubmed_id', 'start', 'end', 'term', 'type', 'tag_id'], delimiter="\t", quoting=csv.QUOTE_NONE)
```
This fix assumes that the null byte comes at the end of the line. If error occurs again, will look into other possible solutions.

**Comment by kengcher** [comment]
great! it works!

Is there a way to use pubtator to parse a text into their tags and
frequencies?

Thank you.

**Comment by danich1** [comment]
Take a look at the `extract_tags.py` script. This script is designed to extract tags from the pubtator xml file. Command to use is:
```bash
python scripts/extract_tags.py \
  --input data/pubtator-docs.xml.xz \
  --output data/pubtator-tags.tsv.xz
```
Once the process has finished you can easily count the frequency of tags.

**Comment by kengcher** [comment]
Hi David

Thank you and I saw that script.

I was wondering if there's a way to process a non-xml text or string?

**Comment by danich1** [comment]
You mean the tag extraction part correct? Currently, we don't have a pure text parser implemented. We were only concerned with extracting tags solely from pubtator; however, this doesn't erase the possibility of an extension.

**Comment by kengcher** [comment]
Would you be able to point me to the appropriate functions to look at,
basically to perform the annotation function in pubtator: i) identifying
bio-entities and ii) identify relationships between entities.

Thank you.

**Comment by danich1** [comment]
Should be pretty straight forward looking at the function within the `extract_tags.py` script. All it does is open the compressed file then has the etree package do the parsing. In your case you won't need/have access to the etree library as it is specifically designed to parse xml like tags. Instead you will just handle the raw text and parse it based on your situational needs.

> ii) identify relationships between entities.

I want to clarify that this project is only designed to identify tags. It doesn't have the capability to detect relationship between entities. You'd have to look at [other places](https://github.com/snorkel-team/snorkel) for that kind of detection or do a manual inspection of the results.
