### ISSUE TITLE
Unspecified numpy version breaks execute.py

### ISSUE THREAD

**Issue by Mnikley** [greenelab/pubtator#33]
# Steps to reproduce
1. clone repo
2. create and activate virtual environment (Python 3.8)
3. install requirements.txt with pip
4. run `python execute.py --config config_files/pubtator_central_config.json`

# Error
```
(venv) C:\Repos\pubtator>python execute.py --config config_files/pubtator_central_config.json
C:\Repos\pubtator\venv\lib\site-packages\pandas\util\testing.py:27: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  import pandas._libs.testing as _testing
Traceback (most recent call last):
  File "execute.py", line 7, in <module>
    from scripts.download_full_text import download_full_text, merge_full_text
  File "C:\Repos\pubtator\scripts\download_full_text.py", line 10, in <module>
    import pandas as pd
  File "C:\Repos\pubtator\venv\lib\site-packages\pandas\__init__.py", line 182, in <module>
    import pandas.testing
  File "C:\Repos\pubtator\venv\lib\site-packages\pandas\testing.py", line 7, in <module>
    from pandas.util.testing import (
  File "C:\Repos\pubtator\venv\lib\site-packages\pandas\util\testing.py", line 27, in <module>
    import pandas._libs.testing as _testing
  File "pandas/_libs/testing.pyx", line 10, in init pandas._libs.testing
  File "C:\Repos\pubtator\venv\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

# Solution
- Downgrade numpy to *1.23.1*: `pip install numpy==1.23.1`
- Add numpy with specific version to requirements.txt

**Comment by danich1** [comment]
Thanks for looking into this problem. I updated requirements.txt to include the Numpy version. Just to let you know, this package has been depreciated due to the original Pubtator group releasing their own XML files.
